### ISSUE TITLE
Android Studio update deletes templates

### ISSUE THREAD

**Issue by marcin-kozinski** [intrications/material-design-icons-adt-template#2]
Android Studio 1.0 RC 4 entered beta channel last week (hurray!).

Unfortunately verifier that runs as part of the update doesn't like the templates pasted as the setup instruction says. On the attached screenshot you can see a sample of files that are described as "unexpected" and marked for deletion. There is no other way to proceed with the update - you have delete all the templates.

Of course you can manually paste the templates again after the update. But you would need to be doing that after **each** update, which is not perfect, to say the least.

Unfortunately I know nothing about installing templates in Studio, so I have no idea how to fix this. But I hope there is a way to release the templates in another way, which won't conflict with update verification process.

![studio-update-deletes-templates](https://cloud.githubusercontent.com/assets/2088582/5341091/9282a0e2-7ef3-11e4-8840-e4f4e8f1d984.png)

**Comment by benju69** [comment]
Same issue. Maybe you can make a plugin for Android Studio ?

**Comment by intrications** [comment]
Closing because this project is now deprecated in favour of using the build in vector icon creator in Android Studio:

https://developer.android.com/studio/write/vector-asset-studio.html#materialicon
