### ISSUE TITLE
Add custom color option

### ISSUE THREAD

**Issue by icastell** [intrications/material-design-icons-adt-template#3]
Would be great to include the possibility to select a custom color icon, besides black, white and grey given.

Thanks for this amazing plugin!

**Comment by intrications** [comment]
I don't think this is possible with a template. I think it would need to be rewritten as a plugin.

I agree that it would be desirable.

**Comment by intrications** [comment]
Closing because this project is now deprecated in favour of using the build in vector icon creator in Android Studio:

https://developer.android.com/studio/write/vector-asset-studio.html#materialicon
