### ISSUE TITLE
Recommended DP value for actionbar / toolbar icons

### ISSUE THREAD

**Issue by johnjohndoe** [intrications/material-design-icons-adt-template#5]
The tool offers multiple values for the density pixels (18dp, 24dp, 36dp, 48dp). When I want to create a icon for the actionbar or toolbar - what is the correct/recommended icons size then? Please give references to the documentation if available. Please add this advice to the README.md.

**Comment by LOG-TAG** [comment]
I'm facing this same confusion!! don't no which one to select on my Icons Importer Android studio plugin !!

**Comment by intrications** [comment]
@johnjohndoe @LOG-TAG 

As far as I know, the toolbar/actionbar icons should be 24dp within a 48dp touch target.
